/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TraceNRouteImport } from './routes/trace.$n'
import { Route as CountNRouteImport } from './routes/count.$n'

const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceNRoute = TraceNRouteImport.update({
  id: '/trace/$n',
  path: '/trace/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const CountNRoute = CountNRouteImport.update({
  id: '/count/$n',
  path: '/count/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/parent': typeof ParentRoute
  '/prizes': typeof PrizesRoute
  '/count/$n': typeof CountNRoute
  '/trace/$n': typeof TraceNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/parent': typeof ParentRoute
  '/prizes': typeof PrizesRoute
  '/count/$n': typeof CountNRoute
  '/trace/$n': typeof TraceNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/parent': typeof ParentRoute
  '/prizes': typeof PrizesRoute
  '/count/$n': typeof CountNRoute
  '/trace/$n': typeof TraceNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/map' | '/match' | '/parent' | '/prizes' | '/count/$n' | '/trace/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/map' | '/match' | '/parent' | '/prizes' | '/count/$n' | '/trace/$n'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/match'
    | '/parent'
    | '/prizes'
    | '/count/$n'
    | '/trace/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  MatchRoute: typeof MatchRoute
  ParentRoute: typeof ParentRoute
  PrizesRoute: typeof PrizesRoute
  CountNRoute: typeof CountNRoute
  TraceNRoute: typeof TraceNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/$n': {
      id: '/trace/$n'
      path: '/trace/$n'
      fullPath: '/trace/$n'
      preLoaderRoute: typeof TraceNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count/$n': {
      id: '/count/$n'
      path: '/count/$n'
      fullPath: '/count/$n'
      preLoaderRoute: typeof CountNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  MatchRoute: MatchRoute,
  ParentRoute: ParentRoute,
  PrizesRoute: PrizesRoute,
  CountNRoute: CountNRoute,
  TraceNRoute: TraceNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
